# Created by Jekyll Writer
title: 记录学习点点滴滴
author: cat
description: 记录iOS学习的点滴，日后回顾和总结
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: jianghao
github_username: jh653513754
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
